"""fix relationship

Revision ID: c19d16b00f13
Revises: 4c8f4d162a6c
Create Date: 2024-12-01 15:53:09.722323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19d16b00f13'
down_revision: Union[str, None] = '4c8f4d162a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicine', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medicine', 'manufacturer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicine', 'manufacturer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medicine', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
